### PR TITLE
Issue 54

### PR DESCRIPTION
**Pull request by Grana69**
Needs A Complete Testing Suite[ Completed ]
https://gitcoin.co/issue/Bounties-Network/Delphi/54/308

### CODE REVIEW

**Comment by Grana69** [comment]
@mbeylin

**Comment by mbeylin** [comment]
Here are my notes:
from `acceptSettlement.js`
- line 137 has the incorrect error message 
- for the tests on lines 139 and 169, please add another assert which checks that the other party's acceptance of that settlement is false
- line 255 has the incorrect error message 
- you may remove the test on line 257 since it is a copy of the previous test
- the test on line 328 should actually be renamed to state that one may not accept a settlement after it has already been accepted (or multiple settlements for the same claim)

from `extendStakeReleaseTime.js`
- line 33 should use a stake release time which is actually greater than the initial release time
- for tests on lines 67 and 84, please use the conf.deadline value (+ 10 or 20) not the block.timestamp

from `increaseClaimFee.js`
- line 77 should use an increased fee which is actually larger than the initial one
- for the test on line 116, please actually check that the token balance of the stake correctly reflects what's expected (i.e. checks that the tokens were indeed deposited)

from `proposeSettlement.js`
- line 39 please use a settlement amount which is less than the sum of the staker's fee + claim amount
- line 67 please use a settlement amount which is less than the sum of the staker's fee + claim amount
- line 97 please use a settlement amount which is less than the sum of the staker's fee + claim amount
- line 102 wrong error message
- line 126 please make sure the settlement is proposed by the correct party (claimant)

from `ruleOnClaim.js`
- line 80 should be called by the arbiter not dave
- line 104 should be called by the arbiter not dave

from `whitelistClaimant.js`
- should whitelist a new address, not the same claimant which was already whitelisted (can remove the first whitelisting)

from `claimFee.js`
- line 235 incorrect error message

for the reveal vote tests, could you explain why you broke them up into two separate files? It's not currently clear to me.

from `revealVoteAux.js`
-  line 82 should say "after" not before the reveal stage has ended

from `submitRuling.js`
- line 129 wrong error message

Overall this is fantastic work, and I'm thoroughly impressed. Most of these issues are small (wrong copied and pasted error messages, or testing a revert and changing more than just one variable to be incorrect).

In advance of accepting this PR, could you also rebase with the most recent version of `develop` to resolve any conflicts?

I'd be delighted to accept this PR and pay you out once those changes are completed.

**Comment by Grana69** [comment]
If i run reveal vote as one i got this:
https://gist.github.com/Grana69/b123bc13965f32518013f5d3a1a0b022

So my solution was just splitting the file in two parts and it runs fine:
https://gist.github.com/Grana69/941f4aa7d6a03f5d4f1097aa267c3d9f

**Comment by Grana69** [comment]
@mbeylin

**Comment by skmgoldin** [comment]
@mbeylin I started reviewing this, but it's so much code the only way I'm going to _really_ be able to audit it without my eyes glazing over is by adding a bunch of comments to it.

I want to do a big refactor of all my tests anyway to make them Mark-style. This individual seems to have done a lot of good work. I think we should merge this, and I'll add a task for myself to comment all this code (which will also constitute a review) in the course of refactoring the `DelphiVoting` tests.

**Pull request merged**
